import { Inter, Kantumruy_Pro } from "next/font/google";
import "./globals.css";
import Scroll from "@/components/scroll";

const inter = Inter({ subsets: ["latin"] });
const kamtumruy_pro = Kantumruy_Pro({
  weight: "400",
  subsets: ["latin"],
});
export const metadata = {
  title: "CheaDEV",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={kamtumruy_pro.className}>
      <Scroll />
      <body className="bg-gray-200 h-screen ">{children}</body>
    </html>
  );
}
